### ISSUE TITLE
What happened to ext2fsd.com?

### ISSUE THREAD

**Issue by KristaMHill** [matt-wu/Ext3Fsd#17]
Hello folks;
A few days back I heard about ext2fsd and did some reading up on it. Yesterday I decided to download the installer from ext2fsd.com but it appears that the webpage is not reachable.

I found references that version 0.69 has some bug fixes and a cached image of the webpage shows that version 0.69 was released on Nov. 2, only a few weeks back. When I look elsewhere, such as at SourceForge I see version 0.68. I'd prefer the newer version.

Anyone know what the situation is?

**Comment by matt-wu** [comment]
corrected!  Just set 0.69 as default download at SourceForge (it won't update automatically).
Thanks.

**Comment by KristaMHill** [comment]
Thanks much!
