### ISSUE TITLE
How to force ext4 (with source code modification)?

### ISSUE THREAD

**Issue by CodingMarco** [matt-wu/Ext3Fsd#24]
Hello,
Somehow not only ext2fsd but also other windows programs detect the ext4 partition that I want to mount as ext3 or not at all so I can't mount or modify it. I tried fsck.ext4 but it didn't work and the partition seems to be all right from any linux.
So where do I have to modify the source code to force ext2fsd to mount a or any partition as ext4 (it can be quick and dirty...)?

Thanks!

**Comment by sanyarnd** [comment]
@CodingMarco probably yours ext4 partition is formatted with 64-bit feature. There are many ways to check what kind of features are enabled. You can boot with liveCD and check it with 

`dumpe2fs /dev/sdxx | more`

If 64bit flag is present, then you need to get rid of it with [`resize2fs`](http://man7.org/linux/man-pages/man8/resize2fs.8.html), you are particularly interested in `-s` flag:

> -s     
> Turns off the 64bit feature and frees blocks that are no longer in use. 

Execution of disabling 64bit feature will take ~20-30s for 1TB HDD.

@matt-wu @ngkaho1234 by the way, wouldn't it be great to put some info about how to fix it in program itself or website FAQ? People are asking about it for more than 8 months, some are even rolling back to 0.68.

**Comment by Ruedii** [comment]
ext4, is essentially an extension of ext3 and ext2.  Mouting it "as ext3" will not cause any changes to the way it is handled unless ext4 features supported by the driver are installed.
